import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MotionBox from "components/MotionBox";
import TagGroups from "components/TagGroups";
import TypeIt from "typeit-react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className={styles.main}>        
        <TypeIt
          options={{
            strings: ["Huawei OJ - JavaScript Solutions"],
            speed: 60,
            waitUntilVisible: true,            
          }}
        />
        <MotionBox
          animate={{ y: 15, scale: 0.97 }}
          transition={{ repeat: Infinity, duration: 2, repeatType: "reverse" }}
          style={{
            margin: "0px auto",
            maxWidth: "min(400px, 90vw)",
          }}
        >
          <Image
            src="/js.svg"
            width={400}
            height={400}
            alt="Launching Illustration"
          />
        </MotionBox>
        <TagGroups tags={['开心','字符串','动态规划']} />
      </main>
    </div>
  );
};

export default Home;
